version: "3.9"
services:
  app:
    build: .
    image: vote-app:latest
    container_name: vote-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:11
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env